function [BW,maskedImage] = GetBorder(RGB,MASK)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB,MASK) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 24-Nov-2022
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Load Mask
BW = MASK;

% Erode mask with default
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW_erode = imerode(BW, se);

% Erode mask with default
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW_dilate = imdilate(BW, se);

BW = BW_dilate - BW_erode;

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

