function [BW_out,properties] = removeSmallHoles(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 24-Nov-2022
%---------------------------------------------------------

BW_out1 = BW_in;

% Remove portions of the image that touch an outside edge.
BW_out1 = imclearborder(BW_out1);

% Filter image based on image properties.
BW_out1 = bwpropfilt(BW_out1,'Area',[200, 1000000]);

% Get properties.
BW_out = ~BW_out1;

% Filter image based on image properties.
BW_out = ~bwpropfilt(BW_out,'Area',[200, 1000000]);

% Get properties.
properties = regionprops(BW_out1, {'Area', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter'});